using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;

namespace Airtable.EFCore.Metadata.Conventions;

internal sealed class AirtableConventionSetBuilder : ProviderConventionSetBuilder
{
    public AirtableConventionSetBuilder(ProviderConventionSetBuilderDependencies dependencies) : base(dependencies)
    {
    }

    public override ConventionSet CreateConventionSet()
    {
        var set = base.CreateConventionSet();
        set.Add(new TableNameFromDbSetConvention(Dependencies));
        set.Add(new ColumnAttributeConvention(Dependencies));
        set.Add(new KeyShouldBeAutogeneratedConvention());
        return set;
    }
}
