using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;

namespace Airtable.EFCore.Metadata.Conventions;

internal sealed class KeyShouldBeAutogeneratedConvention
    : IPropertyAddedConvention, IPropertyFieldChangedConvention
{
    public void ProcessPropertyAdded(IConventionPropertyBuilder propertyBuilder, IConventionContext<IConventionPropertyBuilder> context)
    {
        if (propertyBuilder.Metadata.IsPrimaryKey())
        {
            propertyBuilder.ValueGenerated(ValueGenerated.OnAdd);
        }
    }

    public void ProcessPropertyFieldChanged(IConventionPropertyBuilder propertyBuilder, FieldInfo? newFieldInfo, FieldInfo? oldFieldInfo, IConventionContext<FieldInfo> context)
    {
        if (propertyBuilder.Metadata.IsPrimaryKey())
        {
            propertyBuilder.ValueGenerated(ValueGenerated.OnAdd);
        }
    }
}