name: Publish NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/uaresponders/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish
      run: dotnet pack ./Airtable.EFCore/Airtable.EFCore.csproj --no-build --verbosity normal --output ./obj/output
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./obj/output/*.nupkg --skip-duplicate --source  https://nuget.pkg.github.com/uaresponders/index.json --api-key ${GITHUB_TOKEN} --no-symbols
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

